### ISSUE TITLE
Action log for non-confirmed user

### ISSUE THREAD

**Issue by webgras** [joomla-projects/privacy-framework#136]
### Steps to reproduce the issue
Setup:
In User Global Options:
Set "New User Account Activation" to "Self"

In frontend:
Register yourself as a new FE user
(email with confirmation link will be sent -->don't confirm!)
(User is not enabled and not activated)
Try to login in frontend
Frontend warning: Warning - Login denied! Your account has either been blocked or you have not activated it yet.

### Expected result
User Action Log in Backend:
"User user2 (not activated) tried to log in to site"

### Actual result
User Action Log in Backend:
"User user2 logged in to site"

### System information (as much as possible)
Joomla! 3.9.0-dev Development [ Amani ] 26-June-2018 15:45 GMT

### Additional comments
As for spam protection, I also tried a non-existing user --> no action log --> as I expected! :)

**Comment by mbabker** [comment]
The action log plugin should actually hook the `onUserAfterLogin` and `onUserLoginFailure` events instead of only `onUserLogin`.

`onUserLogin` is when an account being blocked is set by the user plugin, `onUserAfterLogin` is fired for a successful login, and `onUserLoginFailure` fired for a failed login.

// @alikon @joomdonation

**Comment by joomdonation** [comment]
PR https://github.com/joomla-projects/privacy-framework/pull/142 should address this issue

**Comment by alikon** [comment]
closing as we have a pr #142
