### ISSUE TITLE
com_privacy: Stored consents are plain english

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#168]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402661866

Stored consents are stored as plaintext english. Should this be translateable?

**Comment by brianteeman** [comment]
They are translatable - just the string doesnt exist yet in any language pack so it will always fall back to english

https://github.com/joomla-projects/privacy-framework/blob/efac954db30a1cfe35f5a8aeedbc5c772dbf0bd0/administrator/language/en-GB/en-GB.plg_system_privacyconsent.ini#L7

or are you saying something else??

**Comment by joomdonation** [comment]
We store the translate language item, not the language key. So the stored consent depends on the language which user is using when accepting the consent

Guess @Hackwar want it to be translatable like in action logs component?

**Comment by Hackwar** [comment]
I'm just bringing this up. I'm fine with storing it in a specific language, but we are translating almost everything else, so I wanted to bring this to your attention.

**Comment by mbabker** [comment]
It's awkward because if we store just the language key then we have to be able to translate it back (and you're in essence doing another implementation of the action log human readable message code), but translating it before saving means the body text is stored in whatever language is active, which may be a different language from the super user(s).  Probably best to keep it as is to be honest.

**Comment by infograf768** [comment]
As long as it is not necessary to transmit this to the user her-him-self, agree to keep as is.

**Comment by Hackwar** [comment]
Ok, before we make this more difficult than necessary, I'm closing this one. We are storing the consent in the language and form that the user has agreed to and that is it.
