### ISSUE TITLE
com_privacy: Should it be possible to disable the user action log completely?

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#169]
From this comment by me https://github.com/joomla/joomla-cms/pull/20800#issuecomment-402661866

Should it be possible to disable the user action logging completely?

**Comment by brianteeman** [comment]
sorry I cant find the relevant part in that comment so I don't understand what the "issue" is here

**Comment by Hackwar** [comment]
Sorry, this came up while transfering the issues from the other thread. So I think it isn't technically from #20800. The question is, if we want to add a switch to completely disable the user action log. We could add an on/off switch that stops this in the model.

**Comment by mbabker** [comment]
This is a special case and I don't think it should be configurable in the same way the other actions are because the action log component is being used in part as an audit log for these requests.  Originally I did have `com_privacy` logging as a configurable part of the action log component but it was resulting in double messages (the custom ones in the component and the generic onSave stuff).

**Comment by Hackwar** [comment]
I think I didn't phrase this correctly. I'm not talking about the logging of the activities in the users component, but about the logging in com_actionlogs in general. I'm talking about switching off to write anything into #__action_logs. Right now it seems as if it is expected to create the logging model and then log the action via that. You can disable a lot of the logging by disabling the system actionlog plugin, which would prevent all actionlog plugins from being loaded, but third party code that calls the model directly and not by using a plugin, would not be affected by this.

Maybe you don't want to fill up your DB with the log and want to disable this feature. A switch in the model of com_actionlog would be the best way to do this. One could log when this was disabled/enabled and otherwise simply throw away all logging messages instead of storing them in the DB. Idk if we want such a switch, but I'm bringing this up here so that we can discuss it.

**Comment by mbabker** [comment]
I don't think the component should have a killswitch parameter, to me it'd be like the com_content model or JTable having a killswitch for the hit counter that force disabled the capability no matter what (and yeah I know there's a hit counting param but that is checked in more appropriate places).  If we want to tune whether things are logged then shove it into plugins and make sure the right messages are recorded at the right times (which basically in the case of com_privacy means not logging at onSave events because there are other messages logged around that).

**Comment by Hackwar** [comment]
Ok, so no killswitch. :smile: Closing this one.
