### ISSUE TITLE
Reset all consents on Policy Update

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/privacy-framework#188]
Maybe it would be good to have the possibilty to give the Privacy Policy a Version Number with versioning like. 1.0 -> 1.1 when fixing typos or something and 2.0 if something changed in the contents and then reset all consents because of the new Policy. Does that make sense?

**Comment by mbabker** [comment]
Long and short, as is things aren't coded to support versioning, and short of creating a new content type in `com_privacy` I don't see there being a sane way of supporting this.  The workflow for versioning a privacy policy does not align with the workflow of `com_content` in general and even using plugins to extend the article edit forms you can't modify the rest of the MVC layer without overloading it (and we definitely should not be introducing a "if article type is privacy" switch in the `com_content` code).

**Comment by coolcat-creations** [comment]
Yes but maybe a user gave consent to version x.x.x of the privacy policy?
But the reset all consents, would that work? Because what if you dramatically update the PP ?
Would be good if a message appears: we updated our... need your consent again...

**Comment by mbabker** [comment]
The only way to do that is as I said, creating a new content type in `com_privacy` and duplicating every bit of `com_content` functionality needed to make that work to also be able to adjust the content publishing workflow for privacy policies.  Because `com_content` cannot be used for this workflow.

I'm not saying it's a bad request.  I'm saying that the existing Joomla core capabilities do not support it and to support it means not using `com_content` at all in any of the privacy related stuff (or whatever your preferred content management component is, it really isn't all that farfetched for someone to write a plugin to use K2 or Fabrik or EasyBlog or anything else to manage their policy and the same issue is going to exist with those too).

**Comment by coolcat-creations** [comment]
Sorry i don't get that connection. A button to reset all consents - how is that connected to com_content?

**Comment by coolcat-creations** [comment]
I get often messages from websites to consent to their new policy so I think it'asomething to be aware of. We can do the versioning manually maybe?
Something like "reset due to update" a datefield where the siteowner selects the date of the update and then reset?

**Comment by mbabker** [comment]
A bulk reset/invalidate isn't an option without adding consent types to the data schema, as again the system is designed to log consents for any privacy related activity.  It does not exist only for logging privacy policy consents.

> We can do the versioning manually maybe?

There are things you can do to deal with policy versioning on your own.  But as long as the policy is a `com_content.article` that has no special identifier (because the fact it is a policy article is only known by whatever plugins are marking it as such, there's no distinction of this content type in the `#__content` table) there is honestly not much you could do to use that version data.  So again, short of making a light version of `com_content` to very explicitly deal with a privacy policy and a revision oriented workflow having some sort of versioned policy as a core feature is not an option.

**Comment by coolcat-creations** [comment]
Ok, so how would an Privacy Update scenario look like?  I mean how would a siteowner handle this in his workflow? All consents will be not valid at one point.

**Comment by alikon** [comment]
Send a message to your users to inform them & remove all privacy consent given

**Comment by jeckodevelopment** [comment]
> Send a message to your users to inform them & remove all privacy consent given
that means that there should be an opportunity to remove a specific type of consents with just a few clicks.

**Comment by brianteeman** [comment]
"specific type of consent" - ??

**Comment by jeckodevelopment** [comment]
the consent given to the Privacy Policy

**Comment by alikon** [comment]
you can use this feature
![screenshot from 2018-07-09 08-58-30](https://user-images.githubusercontent.com/181681/42435274-4bcc635c-8356-11e8-9877-c386523e1477.png)

**Comment by brianteeman** [comment]
> that means that there should be an opportunity to remove a specific type of consents with just a few clicks.

my question was that your statement implied that there could be different types of consent. Thats what I was querying

**Comment by jeckodevelopment** [comment]
Yes, given that i can see "Subject" and "Privacy Policy" in the subject column, i was asking for the opportunity to reset only the consents having "Privacy Policy" as subject.
Is that something currently possible or achievable?

**Comment by brianteeman** [comment]
You should only have "privacy policy" in the subject column. It was only designed to log one type of consent but I guess someone could write a plugin for other types of consent. So it is achievable but not currently possiblle

**Comment by Hackwar** [comment]
@mbabker wrote a few posts up, that the system is designed to log several different types of privacy consent. So we have 2 contradicting statements here.

@alikon I can't use that feature. Unless I'm misunderstanding, this would invalidate privacy consents after a period of time. But I would want to have ONE specific place in time, where all consents are invalidated, because I then would have changed my privacy policy. I especially actually don't want my old consents being deleted, but just marked as invalid. Otherwise I have no way to proof that a user has agreed to the previous privacy policy.

**Comment by mbabker** [comment]
> @mbabker wrote a few posts up, that the system is designed to log several different types of privacy consent. So we have 2 contradicting statements here.

Core is only supporting logging of privacy policy consents.  That doesn't mean that it is the absolute only thing we are supporting.  It is entirely conceivable that there are other consents a site owner might need in some circumstances and they could include that tracking in this screen.

So yes, from a core perspective we're only concerned with privacy policy consents.  From an engineering/architectural perspective, the design is not exclusive to privacy policy consents.

**Comment by Hackwar** [comment]
I created a PR that should solve the issues discussed in here. See #224

**Comment by Hackwar** [comment]
Can we close this one in favour of #224?

**Comment by jeckodevelopment** [comment]
i'd say yes! 
Closing as we have a PR #224
