### ISSUE TITLE
Do we need #__action_logs_extensions?

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/privacy-framework#209]
The table #__action_logs_extensions currently is only used in one place, in the LogType JForm Field to create a list of loggable extensions. I'm questioning if we really need that table. Right now there is no way to add a new extension to this easily, you will have to create an install script that adds the entry to the table upon installation or update, with all the overhead that entails.

My proposal would be to add a tag to the manifest and then simply read the manifest_cache field from #__extensions and generate the list from that on the fly. We could then drop #__action_logs_extensions and we would have an automatic way to add new extensions to that field type. The rest could be done similarly for #199.

**Comment by mbabker** [comment]
> My proposal would be to add a tag to the manifest and then simply read the manifest_cache field from #__extensions and generate the list from that on the fly.

We don't have component level hooks/capabilities in the installer library minus a couple of exceptions which are basically system components/interfaces anyway.  So as long as the action log system is entirely contained at the component and plugin level (as in there are no `Joomla\CMS` classes), I wouldn't hack in support for that single component to the installer library.

It's honestly no different than the situation now with seeding the `#__content_types` table to support tags and versioning.  Not saying it's at all optimal, but it's no different than existing precedent and if we're going to solve the issue here for action logs it should be a solution for that integration as well IMO.

**Comment by Hackwar** [comment]
I was about to say that we wouldn't be adding a special feature for this in the installer, since we would just be reading the manifest_cache, but then I noticed that the manifest_cache does not contain the whole XML, but just a subset of the manifest data.

Anyway, extending the manifest cache with the actionlog system plugin by the necessary data should be not that difficult. That would keep the whole thing clean and parsing that cache (even doing a nasty ```manifest_cache LIKE '%"logging":true%'```) wouldn't be a huge performance issue in the places where we are using it.

**Comment by Hackwar** [comment]
While going through other issues, I decided that we should go with the current setup with #__action_logs_extensions. We could do this differently, but that would be to much effort right now for a mostly academic issue. So closing this one.
