### ISSUE TITLE
Admin-Module: 1146 Table '#__privacy_requests' doesn't exist 

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-projects/privacy-framework#214]
### Steps to reproduce the issue
After creating a Privacy-Admin-Module on Control Panel:
![screen shot 2018-07-18 at 13 19 46](https://user-images.githubusercontent.com/8235763/42878540-bfd1e5cc-8a8d-11e8-8153-7d76959f2990.jpg)
### System information
- 3.9-dev (Update from 3.8 by Joomla_3.9.0-dev-Development-Update_Package.zip)
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by mbabker** [comment]
And how exactly are you installing this?  It sounds like you updated a 3.8 site using the packages linked from the main repo's PR?  If so, you've got an issue where the update SQL statements didn't apply for some reason.

**Comment by franz-wohlkoenig** [comment]
1. Setup new Site 3.8 by launch.joomla.org
2. Update to 3.9-dev per Custom Path
--- as i didn't find the Privacy-Module
3. Update from https://developer.joomla.org/privacy-pack/ using Joomla_3.9.0-dev-Development-Update_Package.zip.

**Comment by franz-wohlkoenig** [comment]
will install new.

**Comment by mbabker** [comment]
It's entirely possible updating from 3.9 nightly to the privacy pack packages won't run the SQL updates because of the way core does the version comparison (right now the 3.9 nightly should set the core schema version to "3.9.0-2018-06-02" (`#__schemas` table for extension ID 700), because of that there are a bunch of "3.9.0-2018-05-*" update files from this repo that won't run, but the files newer than that will and you'll end up with the schema version of "3.9.0-2018-07-09" that this repo is at.

In theory the Database > Fix routine will help here, but really it's only a glitch because of this specific update path and when the PR is merged to the main repo everything should be OK.

**Comment by franz-wohlkoenig** [comment]
i wanna test to be save its the "nightly > update"-Thing (and launch is building the next Site).

**Comment by franz-wohlkoenig** [comment]
3.8.10 > Joomla_3.9.0-dev-Development-Update_Package.zip works, thanks.
