### ISSUE TITLE
Diagram of the user (or account) states

### ISSUE THREAD

**Issue by hursku** [joomla-projects/privacy-framework#219]
Issue:
The (active) system has a user in different active states (some transitions have 24 h confirmation windows) and s/he can also be forgotten or in removed  state. You can delete the user after removal, too. 
When there rises need to restore the data of a user, how to verify that the user data is consistent (and e.g. not removed) ?

Solution:
minimum: a user "state machice" diagram with timed transitions to help when working on the backup policy/backup&restore plan.

optimal: backup function that understands the diagram(s of all sites under SSO restore), function that restores user data into a state of the diagram(s)
 
Remark:
the SQL based activity log might be utilized

**Comment by Hackwar** [comment]
There is no backup feature in this and implementing something like this is out of the scope of this project. The privacy feature can only create an export for the user and delete a user and her data. But there is no restore feature for this.

**Comment by hursku** [comment]
Ok.
What about the user privacy data management concept or "state machine" diagram that the project implements ?

**Comment by Hackwar** [comment]
I'm not really sure what you mean. People can fill out a form to request data or request the deletion of the account and after they confirmed their mail address, the admin then executes that request. That is it.

**Comment by mbabker** [comment]
There is no state machine diagram.  Workflow is basically this:

- All requests created as "Pending"
- If user confirms within 24 hours, request is moved to "Confirmed", otherwise it becomes "Invalid" (TODO - a "cron" to automatically invalidate requests past 24 hours, but right now that's done if the user tries validating after the time expires)
- Once confirmed, the site administrator can move a request to either "Completed" or "Invalid" based on their action
- A "Completed" or "Invalid" request cannot be transitioned anywhere else, we consider it a closed request with no further action
