### ISSUE TITLE
Cookies, Local Storage and EU regulation 

### ISSUE THREAD

**Issue by schnuti** [joomla-projects/privacy-framework#50]
As I understand it there are 2 x 2 levels in the privacy regulations GDPR and Cookie Regulation.
[Cookie regulation](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm)
1a. Data on the client device for a guest user. Some cookies are allowed without consent.
1b. Data on the client device after accepting cookies and other data (opt-in). An opt-out is needed.
A policy with information about all data stored on the client and there use has to be available on the site.

2a. Data stored on any server for a guest user with or without cookie consent. Session data, IP, 3d party servers like social networks, ads and ...?
2b. Data stored on any server for a logged in user. Any additional data.
Again you need a policy, now about all personal data stored on the servers and the handling of it.
You can probably use the log in for accepting the policy but you still have the guests.

Is this only about 2b. and personal data stored for identified users? There are 3d. party solutions for EU-cookies acceptance but at least the policy informations are very related. And what about the opt-out option?
Anyway, the site owner needs a lot of information from 3.d party extension developers about cookies and personal data.  

Tip: I got a surprise this morning (mai 25.) as I had a short look on www.washingtonpost.com. If you're not in EU, you can probably use a VPN service with a server in EU.
Are all 18 cookies and 48 KB Local Storage before clicking "Browse now" really EU-legislation conform?

**Comment by mbabker** [comment]
We are not putting a cookie consent platform in core.  So anything related to that is off the table.

#37 adds documentation/reporting capabilities about core features as it relates to personal info.  Of the three cookies (unless I missed something) core does generate, 1 is required (session), 1 is entirely opt-in (remember me), and 1 is based on the user's behavior to remember their preference (language switcher).

Core on its own collects very little information that is stored long term (basically, the users table is it).  Everything else is related to the Joomla session structure or associated with our logging tools.

What this repo is going to have by the time it reaches MVP for inclusion to 3.9 is a lot similar to what WordPress added in their 4.9.6 release with some extras on top of that:

- System to manage information requests (right to see data and right to be forgotten basically)
- System to allow extensions to report their privacy related capabilities to assist with forming site specific policies (this reporting may be later expanded to the frontend user submission forms to explicitly inform users what they get on an export or what may be removed, but that is outside MVP and the initial scope to complete a release)
- A consent checkbox for core mail forms ("I agree to allow my data to be processed by email" type deal since the only form submissions that get saved are the privacy related forms, go figure)
- [WIP] A consent to site policy system (#49)
- [WIP] An audit log system (#20)
- [TODO] A system for extensions to provide information for an export request
- [TODO] A system for extensions to remove data upon request

That's really the high level overview and what I consider is the must haves in place before we can tag a beta release.

**Comment by brianteeman** [comment]
+100 to what @mbabker just said

**Comment by schnuti** [comment]
@mbabker Thanks for the answer.
Yes, I do not see any problems with the Joomla! core cookies as long as a description is included with the policy. It comes with Social Media, Ad servers and analytics.

Maybe it's an overkill but there is an IP-address in the content_rating that has no time limit. It may be overwritten, maybe not. A date in the table would be needed to clear the IP.

**Comment by mbabker** [comment]
The vote would need to be cleared in that case too, or the entire rating system rewritten in a way where it can be maintained without storing IP addresses.  Part of it is a legitimate protection mechanism to prevent rating fraud (otherwise a user can sit there and rate something however many times they wish to game the system).  So as designed the rating system can't have IP address anonymization/removal without removing the associated data.

**Comment by schnuti** [comment]
I know that the IP is needed: I though do not think it has to be a valid IP in there for ever. But the date needed to clear (e.g. add a blank if other value like null or empty fails ) is missing. I've cleared this field many times in test cases. 
If a user can add a new rating e.g. every 2. month, I would accept it. As is, he can add a new rating every minute if he cooperates with a friend. 
As I said, it might be overkill. Read It more as information that the IP is used in a db table.

**Comment by mbabker** [comment]
Either way it requires a major refactoring of the feature and how it works and that is beyond scope of what we are doing in this repo.

**Comment by mbabker** [comment]
Wrong button.

**Comment by schnuti** [comment]
So where do the LogRotate plug in belong? Core? As I understood it, the plug in would prevent storing IP's for a longer time. I had a look and will give it a try, if I find out how to use namespaced PHP in the plug in.

**Comment by mbabker** [comment]
We'll do log rotation in core, but IMO that shouldn't hold up getting a 3.9 release out the door.  See #16 for more discussion on that.

**Comment by brianteeman** [comment]
Closed
