### ISSUE TITLE
Com_privacy Options ?

### ISSUE THREAD

**Issue by garstud** [joomla-projects/privacy-framework#52]
The **config.xml** file is currently empty. Is there a reflection on its completion?

I'm a GDPR newbie. Does it makes sense to have, for example:
1. delay for confirmation token seems to be hardcoded to 24h ? does we have to set a param for this value ?
2. the email sent to user to ask him to confirm the request contains 2 urls. Perhaps, it will be great to provide a parameter to decide if the confirmation email will display 1 or 2 links ?

**Comment by mbabker** [comment]
> delay for confirmation token seems to be hardcoded to 24h ? does we have to set a param for this value ?

IMO there isn't a need to make this configurable.  For users submitting requests on their own, they should be able to pretty quickly get to their email to click the confirmation link.  For admin created requests, these should be because of offline communication with the individual involved and they should be informed they'll need to access their email.  Plus it creates an issue with translations since the email text specifies it's only valid for 24 hours (we'd need a good way of making that part of the text customizable).  We can revisit if this does become a usability problem.

> the email sent to user to ask him to confirm the request contains 2 urls. Perhaps, it will be great to provide a parameter to decide if the confirmation email will display 1 or 2 links ?

It's actually the same URL, the difference is one has the additional query string parameter with the confirmation token to prefill the form on the page, the other requires the user to copy/paste the token from the email.  Also, making this a parameter makes managing translations really awkward as you'd in essence need three language strings (one for each combination of displayed URLs) or we move this to a HTML layout but that too is awkward for dealing with translations when you have paragraphs of text (of course nothing stops you from overriding the language string and customizing the text for your site, the only limitations are on the placeholders that are available for use).

Right now, I don't know if there actually will be any component parameters for com_privacy when we ship.  It's easy to delete the empty file when we're ready to send the PR to the main repo, but for now I say keep it since it's already there.

**Comment by mbabker** [comment]
There's now something in the options.
